"""merge referral attribution and user approval status heads

Revision ID: 5b8296a8b7a1
Revises: c4f81b2ad930, f3b8a1d9e2c5
Create Date: 2026-08-31 15:25:17.367667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # SQLModel column types (e.g. AutoString) appear in autogenerated migrations


# revision identifiers, used by Alembic.
revision: str = '5b8296a8b7a1'
down_revision: Union[str, Sequence[str], None] = ('c4f81b2ad930', 'f3b8a1d9e2c5')
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    pass


def downgrade() -> None:
    """Downgrade schema."""
    pass
