"""merge referral competition and performance-payout/referral-rewards heads

Revision ID: b3d7f1a4c8e9
Revises: a7e4c2b8d016, f4b8e2a9c6d3
Create Date: 2026-09-10

Two independent chains both branched off e83c26d1f409 (visit claims):
a7e4c2b8d016 (referral competition/leaderboard) and f4b8e2a9c6d3 (the earlier
merge of performance-cashback-payout with referral-rewards/visit-claims). No
schema overlap between the two, so this merge revision needs no operations
of its own.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # SQLModel column types (e.g. AutoString) appear in autogenerated migrations


# revision identifiers, used by Alembic.
revision: str = 'b3d7f1a4c8e9'
down_revision: Union[str, Sequence[str], None] = ('a7e4c2b8d016', 'f4b8e2a9c6d3')
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    pass


def downgrade() -> None:
    """Downgrade schema."""
    pass
