"""merge performance-cashback-payout and referral-rewards/visit-claims heads

Revision ID: f4b8e2a9c6d3
Revises: a6c3f9d1b8e4, e83c26d1f409
Create Date: 2026-09-10

Two independent chains both branched off b7d4c9e15f80 (merchant membership
billing): a6c3f9d1b8e4 (AQS/performance-cashback, on jay) and e83c26d1f409
(referral rewards, visit claims, email verification, member payouts,
automated receipt checks, on main). No schema overlap between the two, so
this merge revision needs no operations of its own.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # SQLModel column types (e.g. AutoString) appear in autogenerated migrations


# revision identifiers, used by Alembic.
revision: str = 'f4b8e2a9c6d3'
down_revision: Union[str, Sequence[str], None] = ('a6c3f9d1b8e4', 'e83c26d1f409')
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    pass


def downgrade() -> None:
    """Downgrade schema."""
    pass
